Repository salesforce/rules_spring, pull requests merged in 2024-12, with the labels that each got.

#214 Add the deps filter mechanism and update docs and examples.
  examples/demoapp/BUILD
  examples/demoapp/demoapp_dupeclass_allowlist.txt
  springboot/deps_filter_transitive.bzl
  springboot/unwanted_classes.md
Labels: enhancement, 2.4.1

#219 Forward restricted_to and target_compatible_with attributes to rules
  springboot/springboot.bzl
Labels: cla:missing

#220 upgrade examples to Boot3
  README.md
  examples/demoapp/BUILD
  examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java
  examples/helloworld/BUILD
  maven_install.json
  repositories.bzl
  spring_boot_starter_jetty_install.json
  springboot/import_bundles/BUILD
Labels: boot3

#225 BZLMOD: move repo to use bzlmod for everything, delete WORKSPACE
  MODULE.bazel
  MODULE.bazel.lock
  WORKSPACE
  examples/demoapp/BUILD
  makerelease.sh
  maven_install.json
  repositories.bzl
  spring_boot_starter_jetty_install.json
  springboot/unwanted_classes.md
  tools/buildstamp/get_workspace_status
  tools/python_interpreter/BUILD
  tools/python_interpreter/README.md
  tools/python_interpreter/check_python_path.py
Labels: enhancement, COMPAT-BREAK, 2.5.0

#226 Fix shebang in bazelrun wrapper
  springboot/springboot.bzl
Labels: cla:missing

#228 Fix launcher to not require --legacy_external_runfiles
  springboot/springboot.bzl
Labels: cla:missing

#231 enhance docs for attributes
  README.md
  springboot/README.md
  springboot/springboot_doc.md
Labels: enhancement
