Repository salesforce/rules_spring, pull requests merged in 2024-01, with the labels that each got.

#179 Include META-INF/services folder
  springboot/springboot_pkg.sh
Labels: cla:signed, boot3

#178 Add support for passing new Spring Boot JarLauncher class
  springboot/springboot.bzl
  springboot/springboot_pkg.sh
  springboot/write_manifest.sh
Labels: cla:signed

#187 Fix spelling
  examples/demoapp/src/main/java/com/sample/SampleAutoConfiguration.java
  makerelease.sh
  springboot/cli.md
  springboot/springboot.bzl
  springboot/springboot_pkg.sh
  springboot/src/main/java/com/salesforce/rulesspring/index/IndexOfFiles.java
Labels: cla:missing
